### ISSUE TITLE
stubbing method still results in method superclass being called

### ISSUE THREAD

**Issue by slackmage** [drewbourne/mockolate#19]
Heres the contents of my test:

stub(loginDelegate).method("login").args( array("username", "password") );

mock(loginDelegate).method("login").args( array("username", "password") ).twice();

loginDelegate.login("username", "password");
loginCommand.execute("UserName", "PassWord");

verify(loginDelegate);

I have a breakpoint within the loginDelegate.login() method ad it fires twice in this case. After stubbing the method I'm expecting it to not fire at all.

**Comment by slackmage** [comment]
Sorry, I wasn't getting how closely related sub and mock were. The test should actually look like this:

[Test]
        public function loginCommandDoesAToLower() : void {

```
        var loginCommand:LoginCommand = new LoginCommand();
        loginCommand.loginDelegate = loginDelegate;

        stub(loginDelegate).method("login").args( array("username", "password") );

        loginCommand.execute("UserName", "PassWord");

        verify(loginDelegate);

    }
```

**Comment by drewbourne** [comment]
Can you also post the code to LoginCommand and LoginDelegate, there is not enough context to your examples.

**Comment by slackmage** [comment]
https://www.dropbox.com/s/zajrnzs7s2ayliv/stub_failure.zip

**Comment by slackmage** [comment]
method that is stubbed sets true if fired - test tries to false to prove that the method was stubbed and hasn't fired.

**Comment by drewbourne** [comment]
There are two issues at work here. 1) is usage, 2) is a bug. 

1) In your example you are telling Mockolate to set an expectation that login should be invoked like this: 

```
loginDelegate.login( [ "username", "password" ] );
```

Which is not how you are calling it. `.args()` is a `...rest` method. It takes the args as you would invoke a method normally. eg:

```
stub(loginDelegate).method("login").args("username", "password");
```

2) Floxy, the library that generates the Mock Object proxies, doesn't correctly create proxies for Classes that are in the default package. Move the classes you intend to create mocks for to a package and it will work as expected. 

I've opened a new issue for 2).

**Comment by slackmage** [comment]
Thanks drew. I've got this working now.
