### ISSUE TITLE
Allow mocking of namespaced methods and properties

### ISSUE THREAD

**Issue by drewbourne** [drewbourne/mockolate#21]
Examples include mocking the Proxy `flash_proxy` methods, `mx_internal` etc.

Will require changes to FLemit, FLoxy.

**Comment by drewbourne** [comment]
Note: Some of the below may be slightly inaccurate but its enough to remind me of what to look at. 

Gotcha: FLoxy should allow proxying of properties in constructors. For some reason InterceptorProxyListener bails out when in constructors instead of forwarding to Mockolate.

Gotcha: unlike public methods and properties namespaced methods and properties should default to calling the super method unless an expectation is defined.

Triggering use case: Classes such as HTTPService do work in their constructor that access namespaced properties. At the moment FLoxy doesn't allow accessing any of the proxied properties until after the constructor has completed.

**Comment by drewbourne** [comment]
Further progress, FLoxy ProxyGenerator does not forward the namespace to the interceptor. FLoxy hacking begins.

**Comment by gburch** [comment]
What is the latest on this? Any luck?

**Comment by drewbourne** [comment]
It is available in 0.11. With the caveat that the class you are mocking does not contain any methods or properties marked `final`. This is due to a `flash.utils.describeType()` not indicating if a method or property is `final`. A fix is in the works.

**Comment by drewbourne** [comment]
Done in master. See issue 42 for further work. Issue around `final` will be fixed separately.
