### ISSUE TITLE
Allow Partial Mock Objects

### ISSUE THREAD

**Issue by drewbourne** [drewbourne/mockolate#22]
A Partial Mock Object should by default call the super method or property unless an Expectation has been defined.

**Comment by drewbourne** [comment]
Partial mocks can now be used by setting the mock type of "partial". 

```
[Mock(type="partial")]
public var target:SomeClass;
```

**Comment by diazruy** [comment]
Is there a way to create an instance with arguments? There doesn't seem to be a partial() method, and if I create an instance with nice() or strict(), the partial behaviour doesn't seem to be there (with nice, the call to the unstubbed method does nothing, with strict I get complaints about methods being called on the mock that are not expected)

**Comment by drewbourne** [comment]
Whoops, I meant to add `partial()` as a standalone function and available from the `MockolateRule`.  Obviously I haven't done it yet. 

Once I add them you'll be able to call those functions with the constructor args you need, just like `nice()` and `strict()`. 

I'll get the changes up ASAP.

**Comment by drewbourne** [comment]
Changes are in `master`. You should be able to create a partial Mock Object with `partial(YourClass, "yourInstance", [arg1, arg2])`

**Comment by diazruy** [comment]
Whoa! That was fast. I'll take 'er for a spin and let you know. Many thanks

**Comment by diazruy** [comment]
Works like a charm. Thanks
