### ISSUE TITLE
Add build target for AS3-only SWC

### ISSUE THREAD

**Issue by drewbourne** [drewbourne/mockolate#23]
Exclude HTTPServiceDecorator and other classes that have Flex dependencies.

**Comment by nicko** [comment]
Yes please.

**Comment by drewbourne** [comment]
Worked on it today, expect an AS3-only download sometime tomorrow.

**Comment by drewbourne** [comment]
Check downloads for `mockolate-0.11.0.zip`, it contains two SWCs: 1) AS3-only and 2) with Flex.
