### ISSUE TITLE
Incorrect count in test spy

### ISSUE THREAD

**Issue by andreslozadamosto** [drewbourne/mockolate#29]
I tried to use spy test but I had problems when the test checked how many the methos was executed.

Example:

contextPart = nice(IXMLAContextPart);
_xmlaPart.context = contextPart;
mock(contextPart).getter("nodeDepth").returns(1);
mock(contextPart).method("useRootNode").returns(true);
mock(contextPart).method("template").returns(<root><data></data></root>);
mock(contextPart).method("validate").args(anyOf(equalTo("var_1"),equalTo("var_2"))).returns(true);
mock(contextPart).method("validate").args("NO_VALIDATE_AND_DONT_ADD").returns(false);

_xmlaPart.add("var_1", "HOLA");
_xmlaPart.add("var_2", "HOLA2");
var xml:XML = _xmlaPart.generate();

assertThat(contextPart, received().method('template').noArgs().times(1));         //not works. If I use 2 times, the test past... but only once is executed inside generate() funcion
assertThat(contextPart, received().method("useRootNode").noArgs().times(2)); //not works. Same of previous. 
assertThat(contextPart, received().method("useRootNode").twice());                 //not work
assertThat(contextPart, received().getter("nodeDepth").times(1));                     //works fine
assertThat(contextPart, received().method('validate').args(anything()).times(2));  //works fine

generate() function use internaly "nodeDepth", "useRootNode" and "template" once each.

**Comment by andreslozadamosto** [comment]
Sorry, I forgot this.

"nodeDepth", "useRootNode" and "template" are used one time internally for generate function.

Could you help me to resolve this issue, please? Thanks!

**Comment by andreslozadamosto** [comment]
Sorry, I wrote bad code

assertThat(contextPart, received().method("useRootNode").once()); //not work
assertThat(contextPart, received().method("useRootNode").twice()); //work fine

But... only one time is used this method.

Regards

**Comment by drewbourne** [comment]
Did you mean to close this issue? I'm taking a look at this tonight.

**Comment by andreslozadamosto** [comment]
Hi drew!

No, only I wrote bad the example.

The problem still happen.
