### ISSUE TITLE
Preparing and Creating Mockolates from interfaces?

### ISSUE THREAD

**Issue by zd-dalibor** [drewbourne/mockolate#40]
I tried to create Mockolate form interface with:

``` as3
[Rule]
public var mocks:MockolateRule = new MockolateRule();

[Mock]
public var mockIExample:IExample;
```

but I got this error:

```
Illegal override of  IExample
```

where `IExample` is an interface.

**Comment by drewbourne** [comment]
Closing as I cannot reproduce it. 

If this is still an issue, fee free to reopen the issue with an example project that demonstrates the issue.
