### ISSUE TITLE
mocking spark.components.Window

### ISSUE THREAD

**Issue by msamujlo** [drewbourne/mockolate#41]
I my test i'm preparing mock of subclass of spark.components.Window, like this:

``` as3
        [Before(async, timeout=6000, order=1)]
        public function prepareMockolates():void {
            // SplashWindow is mxml component based on spark.components.Window
            Async.proceedOnEvent(this, prepare(SplashWindow), Event.COMPLETE);
        }

        [Before(order=2)]
        public function setUp():void {
            ...
            view = nice( SplashWindow );
            ...
        }
```

After update to version 0.11.0 test failed with this error:

```
VerifyError: Error #1053: Illegal override of mx.core::UIComponent/http://www.adobe.com/2006/flex/mx/internal::$removeChild() in asmock.generated.SplashWindow10E410F4882BDD7AD3A3288A2E60E403F04302CC.
    at flash.system::ApplicationDomain/getDefinition()
    at Function/org.floxy:ProxyRepository/org.floxy:IProxyRepository:prepare/org.floxy:swfLoadedHandler()[/Users/drew/Development/workspace-burrito/floxy/floxy/src/org/floxy/ProxyRepository.as:184]
```

I'm using flex sdk 4.1 and flexunit 4.1. With mockolate v0.10.0 this error didn't show up.

**Comment by drewbourne** [comment]
I enabled mocking of namespaced methods in 0.11. I'll check it out.

**Comment by drewbourne** [comment]
Ahh, `mx.core.UIComponent.mx_internal::$removeChild()` (and a quite a few others) is `final`. The proxy generator is incorrectly generating override methods for those methods. Thanks for reporting this.

**Comment by msamujlo** [comment]
Thanks for super fast response!

**Comment by drewbourne** [comment]
Fixed in master. 

The namespaces to proxy must now be explicitly defined. See https://github.com/drewbourne/mockolate/issues/42 if you want to allow mocking of any namespaced methods.

**Comment by MurrayFurtado** [comment]
Hi Drew,

I was trying to mock a view class (ie subclass of UIComponent) and got the same error. This was using v0.11.0. I saw this thread, so grabbed the latest master source code from git, built the mockolate.swc locally and tried using it, but still got the same error having annotating the mock with [Mock(namespaces="mx.core.mx_internal")]. So I reverted to v0.10.0 and the issue disappeared, so looks like this is still a problem, unless I've done something wrong... Think you need to reinvestigate this one. Thanks!
