### ISSUE TITLE
FlexUnit 4.1 CIListener doesn't like mockolate?

### ISSUE THREAD

**Issue by gavJackson** [drewbourne/mockolate#45]
Hi Drew

I have written a test case which relies heavily on mockolate and have all my tests running and passing through the FlexUnit view in FlashBuilder4.5.

I also have an ant task that executes all my flex unit tests via a CIListener and generates a report.  Weird thing is, when I run the tests through ant (and eventually on my build server) the ones using mockolate error ....even though they were working in Flashbuilder.  

I have made sure FB and ant are both using the same version of Flex Unit 4.1 RC2.

The two errors I seem to be getting when running the ant script are:

Error #1065: Variable org.hamcrest.collection::emptyArray is not defined.

ReferenceError: Error #1065: Variable org.hamcrest.collection::emptyArray is not defined.
at mockolate.ingredients::Mockolatier/prepare()[/Users/drew/Development/workspace-burrito/mockolate/mockolate/src/mockolate/ingredients/Mockolatier.as:81]
at mockolate.runner.statements::PrepareMockClasses/evaluate()[/Users/drew/Development/workspace-burrito/mockolate/mockolate/src/mockolate/runner/statements/PrepareMockClasses.as:50]

AND

A proxy for uk.digitalkeystone.core.view.components::INavButtons has not been prepared yet

ArgumentError: A proxy for uk.digitalkeystone.core.view.components::INavButtons has not been prepared yet
at org.floxy::ProxyRepository/create()[/Users/drew/Development/workspace-burrito/floxy/floxy/src/org/floxy/ProxyRepository.as:55]
at mockolate.ingredients.floxy::FloxyMockolateFactory/create()[/Users/drew/Development/workspace-burrito/mockolate/mockolate/src/mockolate/ingredients/floxy/FloxyMockolateFactory.as:57]

This is my test case for a RL mediator, the actual mediator and view are both really simple, but let me know if you need to see the source code.

```
public class NavButtonsMediatorTest
{       
    [Rule]
    public var rule:MockolateRule = new MockolateRule();

    [Mock]
    public var view:INavButtons;

    private var classUnderTest:NavButtonsMediator;

    [Before]
    public function setUp():void
    {
        classUnderTest = new NavButtonsMediator();
        classUnderTest.backButtonClickedOut = new BackButtonClickedSignal();
        classUnderTest.nextButtonClickedOut = new NextButtonClickedSignal();
        classUnderTest.screenIndexChangedIn = new ScreenIndexChangedSignal();
        classUnderTest.toggleNavigationEnabledIn = new ToggleNavigationEnabledSignal();

        classUnderTest.view = nice(INavButtons);
        mock(classUnderTest.view).getter("backButtonClickedOut").returns(new BackButtonClickedSignal());
        mock(classUnderTest.view).getter("nextButtonClickedOut").returns(new NextButtonClickedSignal());
        mock(classUnderTest.view).setter("currentIndex").arg(int);
        mock(classUnderTest.view).setter("total").arg(uint);
        mock(classUnderTest.view).setter("enabled").arg(Boolean);

        classUnderTest.onRegister();
    }

    [After]
    public function tearDown():void
    {
        classUnderTest.onRemove();
        classUnderTest = null;
    }

    [BeforeClass]
    public static function setUpBeforeClass():void
    {
    }

    [AfterClass]
    public static function tearDownAfterClass():void
    {
    }

    //--------------------------------------------------------------------------
    //
    // Verify that the total and currentIndex of the view are set in response to an incoming ScreenIndexChangedSignal
    //
    //--------------------------------------------------------------------------

    [Test(order="1")]
    public function screenIndexChangedIn__viewTotalAndCurrentSet():void
    {
        // Arrange

        // Act
        classUnderTest.screenIndexChangedIn.dispatch(0,4);

        // Assert
        assertThat(classUnderTest.view, received().setter("total").arg(4).times(1));
        assertThat(classUnderTest.view, received().setter("currentIndex").arg(0).times(1));
    }

    //--------------------------------------------------------------------------
    //
    // Verify that BackButtonClickedSignal is dispatched when the view back button is clicked
    //
    //--------------------------------------------------------------------------

    [Test(async,order="2")]
    public function backButtonClicked__signalForwarded():void
    {
        // Arrange

        // Assert
        proceedOnSignal(this, classUnderTest.backButtonClickedOut);

        // Act
        classUnderTest.view.backButtonClickedOut.dispatch();
    }

    //--------------------------------------------------------------------------
    //
    // Verify that NextButtonClickedSignal is dispatched when the view next button is clicked
    //
    //--------------------------------------------------------------------------

    [Test(async,order="3")]
    public function nextButtonClicked__signalForwarded():void
    {
        // Arrange

        // Assert
        proceedOnSignal(this, classUnderTest.nextButtonClickedOut);

        // Act
        classUnderTest.view.nextButtonClickedOut.dispatch();
    }

    //--------------------------------------------------------------------------
    //
    // Verify that the view is enabled or disabled based on the incoming ToggleNavigationEnabledSignal payload
    //
    //--------------------------------------------------------------------------

    [Test(order="4")]
    public function toggleNavigationEnabledIn_true_viewEnableSet():void
    {
        // Arrange

        // Act
        classUnderTest.toggleNavigationEnabledIn.dispatch(true);

        // Assert
        assertThat(classUnderTest.view, received().setter("enabled").arg(true).times(1));
    }

    [Test(order="5")]
    public function toggleNavigationEnabledIn_false_viewEnableSet():void
    {
        // Arrange

        // Act
        classUnderTest.toggleNavigationEnabledIn.dispatch(false);

        // Assert
        assertThat(classUnderTest.view, received().setter("enabled").arg(false).times(1));
    }
}
```

I could of course be massively mis-using mockolate or flex unit so any guidance you could offer will be much appreciated.

Cheers

Gavin

**Comment by drewbourne** [comment]
The error about `emptyArray()` if a version mismatch of hamcrest-as3. Use the one that in the Mockolate libs directory and it should be right. 

With the other error, try changing the line `classUnderTest.view = nice(INavButtons);` to `classUnderTest.view = view` as the MockolateRule will create an instance of the vars marked with [Mock] for you. They default to nice as well. 

Are you using the download version of Mockolate or building from master?

**Comment by gavJackson** [comment]
Ah the missing hamcrest library was due to Flashbuilder referencing it as a library but not actually copying the swc into my project so when the ant script ran it didn't have access to it., I've made a fake libs folder for my ant scripts and copied the hamcrest swc into it and referenced that in my build script and that has sorted it.

also thanks for the tip on using the [Mock] meta data properly.

fyi I am using the download version of mockolate 0.11.0

cheers Drew
