### ISSUE TITLE
resultEvent value not mocking properly

### ISSUE THREAD

**Issue by ghost** [drewbourne/mockolate#5]
Drew

I think I found another possible bug? I am mocking a delegate to return a resultEvent. Inside the code for the Controller, the delegate result returned is correct, but as soon as I exit the controller and come back to the test, the value is not carried through.

This test below fails, with the last Assert returning false, instead of the required true which was set on the mock. When I debug it in the Controller, the value is being set correctly on the model as per the mock, but as soon as I exit the controller, the value is lost.

I tried to catch the ResultEvent.RESULT to see if that is where the value is set, but no luck

Async.handleEvent(this, fixture.eventDispatcher, ResultEvent.RESULT,check,500,null,noEventFired);

Any ideas what I am missing here?

Thanks
Des

Here is an example of it:
# Test

{
[Test(async)]
public function checkUsernameTest_user_exists():void
        {  
            // Create the authenticationEvent the Presenter would have sent
            authenticationEvent = new AuthenticationEvent(AuthenticationEvent.CHECK_USERNAME);
            authenticationEvent.username = testUsername;

```
        var result:Object = true;       // User does exist
        var token:AsyncToken = new AsyncToken();
        var resultEvent:ResultEvent = new ResultEvent(ResultEvent.RESULT, false, false, result, token);

        // Mock the delegate to return an AsyncToken
        mock(loginDelegateMock).method("checkUsernameExists").args(authenticationEvent.username).returns(token).answers(new ResultAnswer(token, resultEvent));

        // Assert that if you receive "false" the USERNAME_EXISTS event is fired
        Async.proceedOnEvent(this,fixture.eventDispatcher,AuthenticationEvent.USERNAME_EXISTS,500,noEventFired);

        // Make a call to the backend to check if this username exists
        fixture.checkUsername(authenticationEvent);

        Assert.assertEquals("Assert that the loginModel.usernameExists has changed in Model:", true, fixture.loginModel.usernameExists);
```

}
}
# Controller

{
        [Mediate(event="AuthenticationEvent.CHECK_USERNAME")]
        public function checkUsername(authenticationEvent:AuthenticationEvent):void {

```
        var checkUsernameResultEvent:Function = function (resultEvent:ResultEvent):void
        {
            // Assign the result to the model
            loginModel.usernameExists = resultEvent.result as Boolean;
        }

        var checkUsernameFaultEvent:Function = function (faultEvent:FaultEvent):void
        {
            // handle fault
        }
```

executeServiceCall(loginDelegate.checkUsernameExists(authenticationEvent.username), 
                checkUsernameResultEvent, checkUsernameFaultEvent);
        }
}
# Delegate (being mocked)

{
public function checkUsernameExists(username:String):AsyncToken
        {
            return authenticationService.isValidUser(username);
        }
}
# Model

{
public class LoginModel{
        public var username:String = "";
        public var password:String = "";
        public var usernameExists:Boolean;
    }
}

**Comment by drewbourne** [comment]
What does `executeServiceCall` do with the AsyncToken and the two `checkUsernameResultEvent`, `checkUsernameFaultEvent` functions?

`ResultAnswer` only calls the result method of any `IResponder`s added to the `AsyncToken`, if you are listening for events then the mock should also have `.dispatches(resultEvent)`

Another possible issue is the `assertEquals` at the end of the test runs synchronously _before_ the resultEvent is dispatched or the AsyncToken responders have a chance to be called. Instead of `Async.proceedOnEvent()` use `Async.handleEvent()` and put the assertEquals inside the eventHandler. 

cheers, 
Drew

**Comment by ghost** [comment]
Drew

It is a Swiz specific function that extends AbstractController. It does the same as this:

var serviceToken:AsyncToken = someService.send();
var asynchRes:AsyncResponder = new AsyncResponder(theResult, theFault);
serviceToken.addResponder(asynchRes);

Could this be the issue? I am mocking the loginDelegate only and not the Swiz specific function. Would it be better to use an AsyncResponder and mock that?

Thanks
Des

**Comment by drewbourne** [comment]
In that case then the issue is that the `assertEquals` is run before the `checkUsernameResultEvent` function has been called. 

ResultAnswer internally calls the AsyncToken responders asynchronously after at least 10 milliseconds. This is to ensure tests and handlers are correctly setup to handle asynchronous responses. 

Change your test to use `Async.handleEvent()` like I described in my previous comment and it will be good to go:

```
[Test(async)] 
public function checkUsernameTest_user_exists():void
{   
    // Create the authenticationEvent the Presenter would have sent
    authenticationEvent = new AuthenticationEvent(AuthenticationEvent.CHECK_USERNAME);
    authenticationEvent.username = testUsername;

    var result:Object = true;       // User does exist
    var token:AsyncToken = new AsyncToken();
    var resultEvent:ResultEvent = new ResultEvent(ResultEvent.RESULT, false, false, result, token);

    // Mock the delegate to return an AsyncToken
    mock(loginDelegateMock).method("checkUsernameExists").args(authenticationEvent.username)
        .returns(token)
        .answers(new ResultAnswer(token, resultEvent));

    function assertUsernameExistsIsSetOnLoginModel():void
    {
        Assert.assertEquals("Assert that the loginModel.usernameExists has changed in Model:", true, fixture.loginModel.usernameExists);
    }    

    // Assert that if you receive "false" the USERNAME_EXISTS event is fired
    Async.handleEvent(this, fixture.eventDispatcher, 
        AuthenticationEvent.USERNAME_EXISTS, 
        assertUsernameExistsIsSetOnLoginModel, 
        500, noEventFired);

    // Make a call to the backend to check if this username exists
    fixture.checkUsername(authenticationEvent);
}
```
