### ISSUE TITLE
Feature Request: Never

### ISSUE THREAD

**Issue by squeedee** [drewbourne/mockolate#6]
```
[Test(given="with an empty list, a Proxy list, and list is observed",
    it="does not call the proxy manager")]
public function it():void {
    withAnEmptyList();
    withAProxyList();
    withListObserved();

    verify(proxyList).method(PROXY_LIST_ADD).atMost(NEVER);
    verify(proxyList).method(PROXY_LIST_REMOVE).atMost(NEVER);
    verify(proxyList).method(PROXY_LIST_RESET).atMost(NEVER);
    verify(proxyList).method(PROXY_LIST_DISPOSE).atMost(NEVER);
}
```

method().never() would be tidier.

**Comment by squeedee** [comment]
Oops should mention

```
private static const NEVER:int = 0;
```

**Comment by drewbourne** [comment]
uncomment `VerifyingCouverture` lines 170-181, and change `times(0)` to `atMost(0)`

```
verify(proxyList).method(PROXY_LIST_ADD).never();
```

I disabled it for some reason previously, can't remember why.

**Comment by drewbourne** [comment]
reenabled. thanks for pointing out it was missing. 

cheers, 
Drew

**Comment by squeedee** [comment]
Hey no worries, thank you very much for your fantastic software :D

**Comment by squeedee** [comment]
Would you mind pushing it so i can stay canonical to your source? :)

**Comment by squeedee** [comment]
Actually, would this be the reason you commented it out? 

```
no invocations with name add
Error: no invocations with name add
```

for the code

```
verify(proxyList).method(PROXY_LIST_ADD).never();
```

I figure it should be a pass :)

**Comment by drewbourne** [comment]
Yes thats the reason it was commented out. When the method/property is not called at all then the verify will fail as there is an implicit `atLeast(1)`. I did it that way originally so that each link in the verify() method chain would assert. 

I can remove the implicit `atLeast(1)` and instead only do the verify after an expected invocation count has been set. That would mean that this line does not verify whether or not the method was called:

```
verify(proxyList).method(PROXY_LIST_ADD)
```

but then makes it possible to correctly do:

```
verify(proxyList).method(PROXY_LIST_ADD).never()
```

Sound good?

**Comment by squeedee** [comment]
It does. however wouldn't that drastically change behaviour a lot of people depend upon?

**Comment by drewbourne** [comment]
Mockolate is not yet 1.0 so API changes should be expected. From my own use I always specify the expected number of calls when using verify with methods or properties. This is the type of use-case that warrants making an API change.

**Comment by squeedee** [comment]
Ok cool. I'm for it then

**Comment by drewbourne** [comment]
change committed.

**Comment by squeedee** [comment]
Cheers dude!
