### ISSUE TITLE
record() and replay() deprecated - replacements needed

### ISSUE THREAD

**Issue by ghost** [drewbourne/mockolate#61]
Verision: 0.12.4 
Problem: There are no replacements for deprecated record() and replay() methods. This in fact disables the record - playback functionality. 
Proposed solution: Write a suitable replacements to make record - playback available, as this is a key functionality.

**Comment by jbarrus** [comment]
They are no longer necessary, expect works without them.  No replacement is needed.

```
expect(something.test());

something.test();

verify(something);
```

**Comment by drewbourne** [comment]
If you are using nice mocks then just use `expect()` as jbarrus mentioned. 

If you are using strict mocks then instead of `record()` and `replay()` wrap the calls to `expect()` like this: 

``` AS3
var something:Something = strict(Something);

expecting(function():void {
    expect(something.test());
});

something.test();

verify(something);
```
