### ISSUE TITLE
Calling allow() or expect() multiple times should override previous invocations

### ISSUE THREAD

**Issue by wmadden** [drewbourne/mockolate#64]
I have tests in which I stub out the basic behaviour of something in the [Before] method of my test class, then need slightly different behaviour in particular tests.

I've found I can use allow() in the [Before] method and expect() in the specific test case and that will work, but I can't use allow() then allow() or expect() and expect() because only the first call seems to have any effect.

**Comment by jbarrus** [comment]
Shouldn't they be sequential rather than overwriting?  expect(one thing) then expect( another thing after )?

**Comment by wmadden** [comment]
I think there's already a way of doing sequential expectations.

**Comment by drewbourne** [comment]
Any Expectations defined with `expect()` are always checked before any defined by `allow()`, and they are checked in the order they are defined. 

I have deliberately not added the ability to reset a mock object to remove expectations or to allow overriding of defined expectations. Until an expectation's invocation count is matched it will always be the first chosen expectation. The default invocation count is `.atLeast(1)`. 

To define a sequence of expectations you must set an expected invocation count using one of: `.never()`, `.once()`, `.twice()`, `.times()`, `.atLeast()` or `.atMost()` in order for an expectation to be satisfied and allow the next defined expectations to be eligible. 

```
expect(target.method()).returns(3).once();
expect(target.method()).returns(5).once();
expect(target.method()).returns(6).once();
```

To force expectations to only be eligible when called in sequence, use `.inSequence()`.

```
var seq:Sequence = sequence('seq');
expect(target.method()).returns(3).once().inSequence(seq);
expect(target.method()).returns(5).once().inSequence(seq);
expect(target.method()).returns(6).once().inSequence(seq);
```

If you want to reset or redefine the expectations my recommendation is to create a new instance of the mock using `nice(Class)` or `strict(Class)` in the specific test case and then define the specific Expectations you require. 

```
[Mock]
public var target:Target;

[Before]
public function setup():void {
    expect(target.method(2, 4, 5)).returns(11);
}

[Test]
public function overrideTargetExpectations():void {
    target = nice(target);
    expect(target.method(1, 2, 3)).returns(6);
} 
```

HTH.
PS. Apologies for the slow reply, I must have missed the notification.
