### ISSUE TITLE
VerifyingCouverture#never does not seem to work

### ISSUE THREAD

**Issue by creynders** [drewbourne/mockolate#65]
I've got the following code in a test:

``` ActionScript
[Test]
public function test_parsePlayerFromData_doesNotUpdateModelWhenReceivesNullish() : void{
    instance.parsePlayerFromData( null );
    verify( mockPlayersModel ).method( 'addPlayer' ).never();
}
```

And although the addPlayer method is never called I get the following error in the runner:

```
Expected : at least <1> invocations of addPlayer() 
but: PlayersModel
(mockPlayersModel).addPlayer() invoked 0/1 (-1) times
```

**Comment by drewbourne** [comment]
Apologies for the very late response. 
This is very true. That API could have been better. 
I recommend using the `received()` matcher instead: 

```
[Test]
public function test_parsePlayerFromData_doesNotUpdateModelWhenReceivedNullish() : void {
    instance.parsePlayerFromData( null );
    assertThat( mockPlayersModel, received().method( 'addPlayer' ).never() );
}
```

**Comment by creynders** [comment]
Hey @drewbourne thanks for responding though, even if it was a little late :smile: 
I figured that one already out in the mean time though. Working on Robotlegs really made me appreciate mockolate. It rocks, although it's a bit opaque here and there.
