### ISSUE TITLE
An interesting use case - iterable.

### ISSUE THREAD

**Issue by squeedee** [drewbourne/mockolate#7]
So here's a requirement for a matcher, and in the first, would like your feedback. 

I often accept `Object` as a parameter type when i actually mean `IIterable` - However there is no `IIterable` interface in as3 that does what i need, which is, require a type that can be iterated over with `for each (.. in ...)`

A matcher for _Iterable_ that simply caught exceptions on `for each (var item:Object in parameterUnderTest)`  would be very handy for letting my tests show the real intent, even if my parameter type cant.

eg: 

`stub(stubTarget).method("addItems").args(Iterable())`

**Comment by drewbourne** [comment]
What do you mean by "simply caught exceptions"? Are you expecting the parameter to through an exception if it doesnt support iteration with `for each`?

**Comment by squeedee** [comment]
Oh wow, im dumb, Object is For-Eachable thus everything is. Can we delete this issue as though i never raised it? 

**Shame**

**Comment by drewbourne** [comment]
done. ;) 

FYI take a look at the Matcher interface in [hamcrest-as3](http://github.com/drewbourne/hamcrest-as3) its pretty straightforward to implement custom matchers for any scenario not covered by the provided matchers.
