### ISSUE TITLE
Can you please provide an example for capture?

### ISSUE THREAD

**Issue by asogor** [drewbourne/mockolate#8]
I am looking for the Easymock style capture where I can get access to the param and do any inspections to it.

**Comment by drewbourne** [comment]
Added this feature today, take a look at [UsingCapturedArguments.as](http://github.com/drewbourne/mockolate/blob/master/mockolate-unit-test/src/mockolate/UsingCapturedArguments.as) for examples. Let me know how that goes for you. 

cheers 
Drew
